#!/usr/bin/perl
BEGIN {
    my $cwd = $0;
    $cwd =~ s/\/\w+$//;
    push( @INC, "$cwd/lib");
}
use strict;
use warnings;
use Android::Gradle;
use Path;
use Android::Module;

my $opt_a;

while (@ARGV) {
    local $_ = shift @ARGV;
    if ($_ eq '-h' || $_ eq '--help') {
        usage();
        exit(0);
    }elsif($_ eq '-a'){
        $opt_a = $_;
    }elsif (/^-./) {
        print STDERR "Unknown option: $_\n";
        usage();
        exit(0);
    }
}

sub usage{
    print "Usage:\n";
    print "  activity -manifest -a   #show manifest info\n";

}

my $gr = new GradleRoot();
my $gradle_root = $gr->root;
my $gradle = new Gradle($gradle_root);

my $module_path = $


print "src :$src\n";

