#!/usr/bin/perl

use lib qw(lib);

use File::Reader;
use File::Writer;
use File::Spec;

#get user home

my $home = $ENV{HOME};
#print "home:$home\n";
my $bash = $home."/.bashrc";

my $cgi_path = File::Spec->rel2abs('.');

my $reader = new Reader($bash);
my $data = $reader->data;

if($data =~ /^export\s+PATH\s*=\s*\$PATH/){
    my $line = "\$PATH:$cgi_path";
    $data =~ s/\$PATH:[\/\w-]+/$line/;
    #print $data;
}else{
    $data = "export PATH=\$PATH:$cgi_path\n$data";
}

my $w = new Writer();
$w->write_new($bash, $data);



